version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: cnxecommerce
      MYSQL_USER: cnxecommerce_user
      MYSQL_PASSWORD: yourpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  springboot-app:
    build: .
    container_name: springboot-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cnxecommerce
      SPRING_DATASOURCE_USERNAME: cnxecommerce_user
      SPRING_DATASOURCE_PASSWORD: yourpassword
    depends_on:
      - mysql

volumes:
  mysql-data:
